### PR TITLE
Update harbour-sailcron-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Update Swedish translation

### CODE REVIEW

**Comment by a-dekker** [comment]
oops, copy and paste mistake :-)

**Comment by eson57** [comment]
I also have a question. I do not understand what's the difference  between following strings.
```
annually (=yearly)
yearly (=annually)
```

**Comment by a-dekker** [comment]
It is the same. Both are valid in the cron, must be some historical reason to have two terms for the same time indication.
Might be more clear to remove one of the options from the selection page.

**Comment by eson57** [comment]
Ok, because I cant find two terms in Swedish. It'll be the same on both strings.

**Comment by a-dekker** [comment]
I had the same issue in Dutch. I translated it as "jaarlijks (@anually)" and "jaarlijks (@yearly)". But it does not make a lot of sense this way.

**Pull request merged**
