### PR TITLE
Create harbour-sailcron-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Don't know if you want translations, but here's Swedish anyway.
Thanks for this gui. Very useful.

### CODE REVIEW

**Comment by a-dekker** [comment]
Not a real surprise to see a translation from you coming my way :-)

For the human readable strings I use cron-descriptor. It has it's own translations, but swedish is missing (https://github.com/Salamek/cron-descriptor/tree/master/locale). You could try a pull request there if you want those strings translated as well.

**Comment by eson57** [comment]
Thanks! I will do that. I was wondering about those strings, but didn't have time to investigate at that moment, so thanks for the lead.

**Comment by eson57** [comment]
cron-descriptor translation done and also pull request.

**Comment by a-dekker** [comment]
I think you forgot a trailing space on line 31, because a space if often missing after "Vid".

Can you tell me your exact lang setting ("echo $LANG" on a terminal)? I wonder if it is sv_SE.UTF-8 or sv_SV.UTF-8

And for some reason the names of the weekdays are not translated in the cron-descriptor project (goes for all languages).

**Comment by eson57** [comment]
Oops! You are right about the missing space and lang settings are sv_SE.UTF-8.

Yes, me to noticed the missing translation of weekdays.

How about the missing translation strings in Sailcron? You are going to fix that, right?   ;)

**Comment by a-dekker** [comment]
Ah, you mean the additional texts on the add/edit page? I will update those.

**Comment by eson57** [comment]
Yes, exactly. There's also a missing string on main page, before adding any cron entries... "No cron entries found for user nemo/root"

**Comment by a-dekker** [comment]
That string was incorrectly quoted. Made two pushes to git now.

**Comment by eson57** [comment]
Great. I guess I should not translate weekdays then? Better leave "SUN" at line 106, for exampel?

**Comment by a-dekker** [comment]
I will look into the weekdays. But you should leave SUN as it is, that is cron syntax you cannot translate.

**Comment by a-dekker** [comment]
I modified the cron-descriptor code so it returns localized day of week strings instead of hardcoded English strings. I will put it in the Sailcron package and also see if the maintainer is interested.

**Comment by eson57** [comment]
That should of course be a welcome improvement. :+1:

**Comment by a-dekker** [comment]
Just checked and sorry, I still forgot two strings in the "Add" page.
You seem to have missed "No cron entries found for user ".

We are close now :-)

**Comment by eson57** [comment]
he he... maybe we should both get some sleep.  :-)

**Comment by a-dekker** [comment]
I do need some sleep, because somehow I still missed a string.
If you can translate
"Range from 1-31. Wildcard (*) means every day. Multiple days like 1-11 or 20,21"
for me as a response I will add it myself and upload a new release.

**Comment by eson57** [comment]
Sorry, I actually logged out and went to sleep after last post. Here's the translation anyway.

"Intervall från 1-31. Jokertecknet (*) betyder varje dag. Flera dagar skrivs som, 1-11 eller 20,21"

**Comment by eson57** [comment]
cron-descriptor translation was accepted and merged.  :)

**Comment by a-dekker** [comment]
I already made use of it in the meantime, but it is better to have the code upstream as well.

**Pull request merged**
